In [1]:
pwd

'C:\\Users\\DERANGULA ASRITHA'

In [2]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[6, 8, 7],
       [1, 6, 3],
       [9, 9, 0]])

In [3]:
# Array Creation operations

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
### Mathematical Functions

In [12]:
import numpy as np
d=np.random.randint(0,10,10)
d

array([1, 7, 3, 6, 3, 6, 9, 3, 1, 7])

In [13]:
print(np.sin(d))
print(np.cos(d))
print(np.tan(d))

[ 0.84147098  0.6569866   0.14112001 -0.2794155   0.14112001 -0.2794155
  0.41211849  0.14112001  0.84147098  0.6569866 ]
[ 0.54030231  0.75390225 -0.9899925   0.96017029 -0.9899925   0.96017029
 -0.91113026 -0.9899925   0.54030231  0.75390225]
[ 1.55740772  0.87144798 -0.14254654 -0.29100619 -0.14254654 -0.29100619
 -0.45231566 -0.14254654  1.55740772  0.87144798]


In [19]:
print(np.arccos(d))
print()
print(np.arcsin(d))
print()
print(np.arctan(d))

[ 0. nan nan nan nan nan nan nan  0. nan]

[1.57079633        nan        nan        nan        nan        nan
        nan        nan 1.57079633        nan]

[0.78539816 1.42889927 1.24904577 1.40564765 1.24904577 1.40564765
 1.46013911 1.24904577 0.78539816 1.42889927]


C:\Users\DERANGULA ASRITHA\AppData\Local\Temp\ipykernel_12876\437330748.py:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(d))
C:\Users\DERANGULA ASRITHA\AppData\Local\Temp\ipykernel_12876\437330748.py:3: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(d))


In [70]:
print(d)
print(np.where((d < -1) | (d > 1)))  # Indices of invalid values

[2 2 3 8 9 3 6 1 3 6]
(array([0, 1, 2, 3, 4, 5, 6, 8, 9], dtype=int64),)


In [71]:
d_clipped = np.clip(d, -1, 1)
print(np.arccos(d_clipped))
print(np.arcsin(d_clipped))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.57079633 1.57079633 1.57079633 1.57079633 1.57079633 1.57079633
 1.57079633 1.57079633 1.57079633 1.57079633]


In [72]:
valid_mask = (d >= -1) & (d <= 1)
print(np.arccos(d[valid_mask]))
print(np.arcsin(d[valid_mask]))

[0.]
[1.57079633]


In [20]:
np.log(d)

array([0.        , 1.94591015, 1.09861229, 1.79175947, 1.09861229,
       1.79175947, 2.19722458, 1.09861229, 0.        , 1.94591015])

In [21]:
np.log2(d)

array([0.        , 2.80735492, 1.5849625 , 2.5849625 , 1.5849625 ,
       2.5849625 , 3.169925  , 1.5849625 , 0.        , 2.80735492])

In [22]:
np.log10(d)

array([0.        , 0.84509804, 0.47712125, 0.77815125, 0.47712125,
       0.77815125, 0.95424251, 0.47712125, 0.        , 0.84509804])

In [23]:
np.e

2.718281828459045

In [24]:
np.log(np.sqrt(2.718281828459045))

0.5

In [25]:
import math
np.log(math.pow(2.718281828459045,0.2867))

0.2867

In [26]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [27]:
x

array([[5, 9, 7],
       [2, 8, 3],
       [3, 2, 3]])

In [28]:
y

array([[6, 9, 8],
       [9, 6, 2],
       [5, 8, 5]])

In [29]:
x+y

array([[11, 18, 15],
       [11, 14,  5],
       [ 8, 10,  8]])

In [30]:
np.add(x,y)

array([[11, 18, 15],
       [11, 14,  5],
       [ 8, 10,  8]])

In [31]:
np.subtract(x,y)

array([[-1,  0, -1],
       [-7,  2,  1],
       [-2, -6, -2]])

In [32]:
np.multiply(x,y)

array([[30, 81, 56],
       [18, 48,  6],
       [15, 16, 15]])

In [33]:
np.divide(x,y)

array([[0.83333333, 1.        , 0.875     ],
       [0.22222222, 1.33333333, 1.5       ],
       [0.6       , 0.25      , 0.6       ]])

In [34]:
np.floor_divide(x,y)

array([[0, 1, 0],
       [0, 1, 1],
       [0, 0, 0]])

In [35]:
d1=np.random.randint(0,10,10)/5
print(d1)
np.ceil(d1)

[0.8 0.4 1.4 1.8 1.4 1.8 1.6 0.2 1.  1.6]


array([1., 1., 2., 2., 2., 2., 2., 1., 1., 2.])

In [36]:
# Mathematical:
#  Arithmetic
#  exponential, log
#  trigonometrics
#  rounding

In [37]:
import numpy as np
d=np.random.randint(0,10,10)
d

array([2, 2, 3, 8, 9, 3, 6, 1, 3, 6])

In [38]:
d[d>5]

array([8, 9, 6, 6])

In [39]:
marks=np.random.randint(0,100,20)
marks

array([65, 20, 16, 71, 11, 84, 54, 46, 30, 86, 23, 33, 52, 13,  5, 31, 59,
       43, 51, 87])

In [40]:
marks[marks>50]

array([65, 71, 84, 54, 86, 52, 59, 51, 87])

In [41]:
marks[marks>np.mean(marks)]

array([65, 71, 84, 54, 46, 86, 52, 59, 51, 87])

In [42]:
marks[marks<np.mean(marks)]

array([20, 16, 11, 30, 23, 33, 13,  5, 31, 43])

In [43]:
# Array manipulation


In [44]:
z=np.random.randint(0,20,(3,3))
z

array([[10,  1,  5],
       [ 1, 17, 10],
       [17,  3,  4]])

In [45]:
np.ravel(z)    # ravel() method is used for falttening the array elements

array([10,  1,  5,  1, 17, 10, 17,  3,  4])

In [46]:
z.T   # T is a transpose of a array it converts rows to columns and columns to rows

array([[10,  1, 17],
       [ 1, 17,  3],
       [ 5, 10,  4]])

In [47]:
z=np.random.randint(0,20,(20))
z.reshape(2,10)

array([[ 3,  2,  6,  8, 10,  0, 19, 13,  9, 13],
       [ 8, 19, 12,  4, 15, 17,  2,  5,  3,  0]])

In [48]:
z.reshape(4,5)

array([[ 3,  2,  6,  8, 10],
       [ 0, 19, 13,  9, 13],
       [ 8, 19, 12,  4, 15],
       [17,  2,  5,  3,  0]])

In [49]:
z.reshape(5,4)

array([[ 3,  2,  6,  8],
       [10,  0, 19, 13],
       [ 9, 13,  8, 19],
       [12,  4, 15, 17],
       [ 2,  5,  3,  0]])

In [50]:
z.reshape(10,2)

array([[ 3,  2],
       [ 6,  8],
       [10,  0],
       [19, 13],
       [ 9, 13],
       [ 8, 19],
       [12,  4],
       [15, 17],
       [ 2,  5],
       [ 3,  0]])

In [51]:
d1=np.random.randint(0,20,(3,3))
d2=np.random.randint(0,20,(3,3))

In [52]:
d1

array([[17,  5, 11],
       [17, 10,  6],
       [ 4,  8,  3]])

In [53]:
d2

array([[ 2, 15,  9],
       [ 5,  6,  1],
       [ 7, 13,  4]])

In [54]:
np.hstack([d1,d2])

array([[17,  5, 11,  2, 15,  9],
       [17, 10,  6,  5,  6,  1],
       [ 4,  8,  3,  7, 13,  4]])

In [55]:
np.vstack([d1,d2])

array([[17,  5, 11],
       [17, 10,  6],
       [ 4,  8,  3],
       [ 2, 15,  9],
       [ 5,  6,  1],
       [ 7, 13,  4]])

In [56]:
data=np.random.randint(0,20,10)
data

array([18, 14, 11, 12,  0, 12,  8, 17, 14,  7])

In [57]:
np.split(data,5)

[array([18, 14]),
 array([11, 12]),
 array([ 0, 12]),
 array([ 8, 17]),
 array([14,  7])]

In [58]:
np.split(data,2)

[array([18, 14, 11, 12,  0]), array([12,  8, 17, 14,  7])]

In [60]:
np.array_split(data, 4)

[array([18, 14, 11]), array([12,  0, 12]), array([ 8, 17]), array([14,  7])]

In [61]:
matrix=np.array([[1,2,3,4] ,[5,6,7,8]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
np.hsplit(matrix,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [63]:
np.hsplit(matrix,4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [64]:
matrix1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [65]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
np.vsplit(matrix1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [67]:
np.vsplit(matrix1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [68]:
np.vsplit(matrix1,[1,3])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [69]:
np.vsplit(matrix1,[1,3])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]