In [1]:
pwd

'C:\\Users\\DERANGULA ASRITHA'

In [2]:
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[10, 40, 55, 42, 12],
       [66, 20,  7, 79, 79],
       [20, 76, 63,  3, 39],
       [36, 78, 31, 99, 37],
       [36, 30, 25, 68, 48]])

In [3]:
type(np.array([1,2,3]))

numpy.ndarray

In [4]:
data[0,0]

10

In [5]:
print(data)
print(" ")
# print(data[-3:-1,-3:-1])

[[10 40 55 42 12]
 [66 20  7 79 79]
 [20 76 63  3 39]
 [36 78 31 99 37]
 [36 30 25 68 48]]
 


In [6]:
data

array([[10, 40, 55, 42, 12],
       [66, 20,  7, 79, 79],
       [20, 76, 63,  3, 39],
       [36, 78, 31, 99, 37],
       [36, 30, 25, 68, 48]])

In [7]:
data[-2:-1,-2:-1]

array([[99]])

In [8]:
x=[1,2,3]
print(type(x))
y=np.array([1,2,3])
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
#differences
# 1. If we perform operations(like +,-,/,*) on list  it throws error showing cannot perform operations on list where as in numpy array it is designed to perfrom all element arithmentic operations
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
y/2

array([0.5, 1. , 1.5])

In [11]:
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,6.0,"data"])

In [12]:
x

[1, 2, 3, 6.0, 'data']

In [13]:
y

array(['1', '2', '3', '6.0', 'data'], dtype='<U32')

In [14]:
### Random family functions

In [15]:
np.random.randint(0,100,(5,10))

array([[44, 44, 44, 79, 13,  0, 16, 21, 87, 47],
       [51,  2, 11, 20, 72, 24, 42, 38, 34, 89],
       [55, 46, 79, 71,  2, 49, 37,  5, 16, 93],
       [74, 94, 40, 17, 45, 35, 26, 23, 37, 61],
       [90, 13, 58,  8, 61, 21, 48, 22, 40, 10]])

In [16]:
np.random.rand(3,3)

array([[0.46955094, 0.56160249, 0.15765994],
       [0.48359703, 0.610947  , 0.26155548],
       [0.69408747, 0.86966672, 0.76743122]])

In [17]:
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [18]:
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [21]:
np.random.rand(3,3)  # rand will give numeric values ranging form 0 to 1

array([[0.8740638 , 0.74311957, 0.99913273],
       [0.59642076, 0.84895241, 0.79018061],
       [0.46618808, 0.91668294, 0.74896727]])

In [22]:
np.random.rand(100)

array([0.21633879, 0.65379416, 0.91439212, 0.56366402, 0.88242774,
       0.72204238, 0.34741244, 0.09628809, 0.45525952, 0.44036788,
       0.39705764, 0.96186539, 0.2919618 , 0.53557129, 0.17735164,
       0.21562854, 0.95925541, 0.38423336, 0.90199816, 0.34514071,
       0.98016589, 0.08466436, 0.10304225, 0.34265815, 0.61025999,
       0.35584475, 0.09926216, 0.96728082, 0.52234586, 0.39257328,
       0.6164476 , 0.15771194, 0.51020135, 0.51328278, 0.03847518,
       0.42937497, 0.85472071, 0.49951807, 0.93918479, 0.55956019,
       0.80333247, 0.24106026, 0.69824146, 0.08709278, 0.48024078,
       0.10806412, 0.31777561, 0.47171102, 0.23499389, 0.81125113,
       0.57871134, 0.78662555, 0.53163073, 0.06357419, 0.0434355 ,
       0.49960849, 0.20845771, 0.55333936, 0.04805352, 0.17868453,
       0.22749357, 0.63922232, 0.67344914, 0.22677724, 0.40284463,
       0.46627243, 0.69540469, 0.48165256, 0.75409635, 0.72259195,
       0.96610134, 0.63645874, 0.45191893, 0.47668809, 0.51354

In [23]:
import numpy as np
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())    # scaling the data , this is also known as normalization of data and it is also known as min-max scaling 

array([0.        , 0.33333333, 0.66666667, 1.        ])