In [1]:
pwd

'C:\\Users\\DERANGULA ASRITHA'

In [2]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[5, 6, 8],
       [1, 9, 2],
       [3, 2, 9]])

In [3]:
import numpy as np
np.random.rand(30,30).mean()

0.49540566742846126

In [4]:
import numpy as np
data=np.random.randint(0,10,(4,4))
data



array([[8, 5, 6, 7],
       [7, 7, 0, 8],
       [9, 3, 8, 0],
       [5, 9, 8, 0]])

In [5]:
np.std(data)

3.0998991919093113

In [6]:
np.var(data)

9.609375

In [7]:
np.mean(data)

5.625

In [8]:
np.median(data)

7.0

In [9]:
data=np.random.randint(0,100,10)
data

array([79, 65, 19, 54, 53, 85, 28, 13, 88, 28])

In [10]:
data.min(),data.max()

(13, 88)

In [11]:
range=data.max()-data.min()
range

75

In [12]:
import numpy as np
dt=np.random.randint(0,20,(5,5))
dt

array([[16, 18,  5, 15,  3],
       [ 8, 15,  3,  7, 14],
       [ 0, 12, 19, 18,  9],
       [ 6, 13, 15,  6, 17],
       [ 1,  3, 12, 19, 18]])

In [13]:
print(dt.sum(axis=0)) #vertical sum
print()
print(dt.sum(axis=1))# Horizontal sum

[31 61 54 65 61]

[57 47 58 57 53]


In [14]:
dt


array([[16, 18,  5, 15,  3],
       [ 8, 15,  3,  7, 14],
       [ 0, 12, 19, 18,  9],
       [ 6, 13, 15,  6, 17],
       [ 1,  3, 12, 19, 18]])

In [15]:
print(dt.min(axis=0))
print(dt.min(axis=1))

[0 3 3 6 3]
[3 3 0 6 1]


In [16]:
print(dt.max(axis=0))
print(dt.max(axis=1))

[16 18 19 19 18]
[18 15 19 17 19]


In [17]:
dt[0:2,0:2].max()

18

In [18]:
dt[-3:,-2:].max()

19

In [19]:
dt[-3:,-2:].min()

6

In [20]:
data=np.random.randint(0,10,10)
data

array([3, 4, 0, 9, 3, 2, 1, 7, 1, 9])

In [21]:
data.min() # min returns the minimum value of an array

0

In [22]:
data.argmin()  # argmin returns the element minimum value of that index in array

2

In [23]:
data.max()

9

In [24]:
data.argmax()

3

In [25]:
import numpy as np
d=np.random.randint(0,10,(3,3))
d

array([[7, 7, 1],
       [9, 0, 3],
       [1, 4, 1]])

In [26]:
d.argmax(axis=0)

array([1, 0, 1], dtype=int64)

In [27]:
d.argmax(axis=1)

array([0, 0, 1], dtype=int64)

In [28]:
d.argmin(axis=0)

array([2, 1, 0], dtype=int64)

In [29]:
d.argmin(axis=1)

array([2, 1, 0], dtype=int64)

In [30]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [31]:
## calculate the total sales 
retail_data[:,1].sum()

335000

In [32]:
##"Which store has the highest inventory, and what is its store ID?"
retail_data[:,3].argmax()+1

9

In [33]:
# sales/customer
# sales/transaction : basket value
# sales/units: basket size

In [34]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [35]:
f=retail_data[:,1]/retail_data[:,2]
print(f)
x=np.argmax(f)
print(x)

[83.33333333 71.11111111 73.68421053 82.         83.33333333 75.
 81.25       75.         81.81818182 80.48780488]
0


In [36]:
data=np.random.randint(0,10,3)
data



array([0, 2, 7])

In [37]:
x=20
data+x

array([20, 22, 27])

In [38]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))
x+y

array([[13, 12,  9],
       [ 7,  6,  3],
       [ 7,  6,  3]])

In [39]:
x

array([[8],
       [2],
       [2]])

In [40]:
y

array([[5, 4, 1]])

In [41]:
import numpy as np
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))


In [42]:
x

array([[0],
       [1],
       [8]])

In [43]:
y

array([[6, 1, 1]])

In [44]:
x*y

array([[ 0,  0,  0],
       [ 6,  1,  1],
       [48,  8,  8]])